# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_sso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='create_user',
            field=models.BooleanField(default=False, help_text="Create a user upon first login for every account. Subsequent logins are done matching account's email address."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='List of groups users should be added to on account creation.', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='make_superuser',
            field=models.BooleanField(default=False, help_text='Whether the created user(s) should be superusers or not.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='domain',
            field=models.CharField(help_text='A domain with Oauth support. Example: mywebsite.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User to be used on login for this assignment. Useful when using a different remote username.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='username',
            field=models.CharField(blank=True, help_text='Example: john', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='username_mode',
            field=models.IntegerField(choices=[(0, 'Any account from the domain'), (1, 'Only an account that matches a specific username'), (2, "All accounts that don't match a specific username")], help_text='Defines which mode/rule will be used to allow accounts to login.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='Specifies the order in which this assignment will be taken into account compared to others.'),
        ),
    ]
